name: Run
on:
  push:
    branches:
      - 'master'

jobs:
  Run:
    name: Run
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: NPM install
        run: npm install

      - name: Run tests
        run: npm run test
        continue-on-error: true
      
      - name: Generate Allure Report
        run: npm run allure:generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report